tasks:
  - name: Install Bun
    init: |
      curl -fsSL https://bun.sh/install | bash
      source /home/gitpod/.bashrc
      gp sync-done bun
  - name: Install Dependencies
    init: gp sync-await bun && bun install
    command: bun run dev
